### ISSUE TITLE
Support for Appendices

### ISSUE THREAD

**Issue by mrautio** [mrautio/hh-templates#5]
In all templates Appendices come after references. Making some sensible way to add appendices would be nice as currently pandoc adds automatic References after the MD file.

**Comment by mrautio-p** [comment]
https://github.com/mrautio/hh-templates/commit/eec9e268cbd2107cebd3554f069c9b08b7d11ba3

**Comment by mrautio** [comment]
Support added

Command example: https://github.com/mrautio/hh-templates#markdown-to-pdf-with-docker
Example attachments file: https://github.com/mrautio/hh-templates/blob/main/attachments.md
